package com.smithware.lastdone

import android.os.Bundle
import android.os.Build
import android.Manifest
import android.content.pm.PackageManager
import android.net.Uri
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.lifecycle.lifecycleScope
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.platform.LocalContext
import androidx.lifecycle.viewmodel.compose.viewModel
import com.smithware.lastdone.data.*
import com.smithware.lastdone.domain.*
import kotlinx.coroutines.flow.collectLatest
import java.text.DateFormat
import java.time.*
import java.util.*
import kotlinx.coroutines.launch

private val Cream=Color(0xFFFFF9ED);private val Charcoal=Color(0xFF2D3028);private val Moss=Color(0xFF637B52);private val Copper=Color(0xFFC47A45);private val Amber=Color(0xFFE0A33A)
class MainActivity:ComponentActivity(){
 private var pendingExport:String=""
 private val createDocument=registerForActivityResult(ActivityResultContracts.CreateDocument("application/octet-stream")){uri->if(uri!=null)lifecycleScope.launch{contentResolver.openOutputStream(uri)?.bufferedWriter()?.use{it.write(pendingExport)};Toast.makeText(this@MainActivity,"Export saved",Toast.LENGTH_SHORT).show()}}
 private val openBackup=registerForActivityResult(ActivityResultContracts.OpenDocument()){uri->if(uri!=null)lifecycleScope.launch{runCatching{val text=contentResolver.openInputStream(uri)?.bufferedReader()?.use{it.readText()}?:error("Could not read backup");val backup=(application as LastDoneApp).repository.validateBackup(text);android.app.AlertDialog.Builder(this@MainActivity).setTitle("Replace current data?").setMessage("Validated ${backup.items.size} items and ${backup.completions.size} completions. Current LastDone data will be replaced only after you confirm.").setNegativeButton("Cancel",null).setPositiveButton("Replace"){_,_->lifecycleScope.launch{(application as LastDoneApp).repository.restoreReplace(backup);Toast.makeText(this@MainActivity,"Backup restored",Toast.LENGTH_SHORT).show()}}.show()}.onFailure{Toast.makeText(this@MainActivity,"Backup rejected: ${it.message}",Toast.LENGTH_LONG).show()}}}
 override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS),42);setContent{val app=application as LastDoneApp;val vm:LastDoneViewModel=viewModel(factory=LastDoneVmFactory(app));LastDoneRoot(vm)}}
 fun exportBackup(){lifecycleScope.launch{pendingExport=(application as LastDoneApp).repository.createBackup();createDocument.launch("LastDone-backup.json")}}
 fun exportCsv(){lifecycleScope.launch{pendingExport=(application as LastDoneApp).repository.createCsv();createDocument.launch("LastDone-history.csv")}}
 fun restoreBackup(){openBackup.launch(arrayOf("application/json","application/octet-stream","text/plain"))}
}

@Composable fun LastDoneRoot(vm:LastDoneViewModel){val settings by vm.settings.collectAsState();val colors=if(settings.darkMode)darkColorScheme(primary=Color(0xFFAEC895),secondary=Color(0xFFE3A779))else lightColorScheme(primary=Moss,secondary=Copper,tertiary=Amber,background=Cream,surface=Color(0xFFFFFCF5),onSurface=Charcoal);MaterialTheme(colors){if(!settings.onboardingDone)Onboarding(vm)else AppShell(vm)}}

@Composable private fun Onboarding(vm:LastDoneViewModel){var page by remember{mutableIntStateOf(0)};val titles=listOf("Remember without the pressure","Record it in seconds","See how long it has been","Reminders only where useful");val bodies=listOf("Add occasional maintenance, care, and personal check-ins.","Tap Done Now whenever you complete an item.","LastDone keeps the history locally on this device.","Choose intervals and local reminders only when they help.");Surface(Modifier.fillMaxSize()){Column(Modifier.fillMaxSize().padding(28.dp),verticalArrangement=Arrangement.SpaceBetween){Column{Text("LASTDONE",style=MaterialTheme.typography.labelLarge,color=MaterialTheme.colorScheme.primary);Spacer(Modifier.height(56.dp));Icon(Icons.Default.History,null,Modifier.size(72.dp),tint=MaterialTheme.colorScheme.secondary);Spacer(Modifier.height(28.dp));Text(titles[page],style=MaterialTheme.typography.headlineLarge,fontWeight=FontWeight.Bold);Spacer(Modifier.height(12.dp));Text(bodies[page],style=MaterialTheme.typography.bodyLarge)};Column{LinearProgressIndicator({(page+1)/4f},Modifier.fillMaxWidth());Spacer(Modifier.height(20.dp));Button({if(page<3)page++ else vm.finishOnboarding()},Modifier.fillMaxWidth().heightIn(min=52.dp)){Text(if(page<3)"Continue" else "Create a blank item")};TextButton({vm.demo();vm.finishOnboarding()},Modifier.fillMaxWidth()){Text("Start with removable demo data")};TextButton({vm.finishOnboarding()},Modifier.fillMaxWidth()){Text("Skip")}}}}}

private enum class Tab{TODAY,ITEMS,HISTORY,SETTINGS}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun AppShell(vm:LastDoneViewModel){var tab by remember{mutableStateOf(Tab.TODAY)};var selected by remember{mutableStateOf<Long?>(null)};var add by remember{mutableStateOf(false)};var completion by remember{mutableStateOf<ItemSummary?>(null)};val snack=remember{SnackbarHostState()};val scope=rememberCoroutineScope();if(selected!=null){DetailScreen(selected!!,vm,{selected=null},{completion=it});return};Scaffold(snackbarHost={SnackbarHost(snack)},topBar={TopAppBar(title={Column{Text("LastDone",fontWeight=FontWeight.Bold);Text("Smithware Studios",style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.primary)}})},floatingActionButton={if(tab!=Tab.SETTINGS)ExtendedFloatingActionButton(text={Text("Add Item")},icon={Icon(Icons.Default.Add,null)},onClick={add=true})},bottomBar={NavigationBar{listOf(Tab.TODAY to Icons.Default.Today,Tab.ITEMS to Icons.Default.List,Tab.HISTORY to Icons.Default.History,Tab.SETTINGS to Icons.Default.Settings).forEach{(t,i)->NavigationBarItem(selected=tab==t,onClick={tab=t},icon={Icon(i,t.name)},label={Text(t.name.lowercase().replaceFirstChar(Char::uppercase))})}}}){pad->Box(Modifier.padding(pad)){when(tab){Tab.TODAY->TodayScreen(vm,{selected=it},{completion=it});Tab.ITEMS->ItemsScreen(vm,{selected=it},{completion=it});Tab.HISTORY->HistoryScreen(vm);Tab.SETTINGS->SettingsScreen(vm)}}};if(add)AddItemDialog(vm,{add=false});completion?.let{DoneDialog(it,{completion=null}){date,note,cost,measurement->vm.done(it.item.id,date,note,cost,measurement){recordId->scope.launch{val result=snack.showSnackbar("Completion recorded","Undo",duration=SnackbarDuration.Short);if(result==SnackbarResult.ActionPerformed)vm.undo(recordId)}};completion=null}}}

@Composable private fun TodayScreen(vm:LastDoneViewModel,open:(Long)->Unit,done:(ItemSummary)->Unit){val all by vm.items.collectAsState();var search by remember{mutableStateOf("")};var filter by remember{mutableStateOf("All")};val visible=all.filter{!it.item.archived&&(search.isBlank()||listOf(it.item.name,it.item.notes,it.categoryName,it.item.associatedPerson,it.item.location).any{s->s.contains(search,true)})}.filter{filter=="All"||it.categoryName==filter};LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("When did I last do this?",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Spacer(Modifier.height(12.dp));OutlinedTextField(search,{search=it},Modifier.fillMaxWidth(),label={Text("Search")},leadingIcon={Icon(Icons.Default.Search,null)},singleLine=true)};item{LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(listOf("All")+all.map{it.categoryName}.distinct()){c->FilterChip(filter==c,{filter=c},{Text(c)})}}};if(visible.isEmpty())item{EmptyCard("Nothing tracked here yet","Add an item or start with a template.")};items(visible,key={it.item.id}){ItemCard(it,{open(it.item.id)},{done(it)})}}}
@Composable private fun ItemsScreen(vm:LastDoneViewModel,open:(Long)->Unit,done:(ItemSummary)->Unit){val all by vm.items.collectAsState();LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("All items",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold)};items(all.filter{!it.item.archived}){ItemCard(it,{open(it.item.id)},{done(it)})}}}

@Composable private fun ItemCard(s:ItemSummary,open:()->Unit,done:()->Unit){val status=LastDoneCalculations.status(s.lastDone,s.item.expectedDays);val label=status.name.lowercase().replace('_',' ').replaceFirstChar(Char::uppercase);Card(Modifier.fillMaxWidth().clickable(onClick=open),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Column(Modifier.padding(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){Surface(shape=RoundedCornerShape(12.dp),color=Color(s.categoryColor).copy(alpha=.18f)){Text(s.item.icon,Modifier.padding(12.dp))};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(s.item.name,fontWeight=FontWeight.Bold,maxLines=2,overflow=TextOverflow.Ellipsis);Text(s.categoryName,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.primary)}};Spacer(Modifier.height(14.dp));Text(LastDoneCalculations.elapsedLabel(s.lastDone),style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text(if(s.lastDone==null)"No history recorded yet" else "Last completion: ${DateFormat.getDateInstance().format(Date(s.lastDone))}");s.item.expectedDays?.let{Text("Usual interval: $it days")};Spacer(Modifier.height(10.dp));Row(verticalAlignment=Alignment.CenterVertically){AssistChip({},label={Text(label)},leadingIcon={Icon(if(status==ItemStatus.OVERDUE)Icons.Default.Info else Icons.Default.CheckCircle,null)});Spacer(Modifier.weight(1f));Button(done){Text("Done Now")}}}}}

@Composable private fun AddItemDialog(vm:LastDoneViewModel,dismiss:()->Unit){val cats by vm.categories.collectAsState();var name by remember{mutableStateOf("")};var cat by remember{mutableStateOf<Long?>(null)};var days by remember{mutableStateOf("")};var notes by remember{mutableStateOf("")};var template by remember{mutableStateOf(false)};LaunchedEffect(cats){if(cat==null)cat=cats.firstOrNull()?.id};AlertDialog(onDismissRequest=dismiss,title={Text(if(template)"Choose a template" else "New tracked item")},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(10.dp)){if(template){Templates.groups.forEach{(group,names)->Text(group,fontWeight=FontWeight.Bold);names.forEach{n->TextButton({name=n;template=false}){Text(n)}}}}else{OutlinedTextField(name,{name=it},label={Text("Name")});Text("Category",fontWeight=FontWeight.Bold);LazyRow{items(cats){c->FilterChip(cat==c.id,{cat=c.id},{Text(c.name)},Modifier.padding(end=6.dp))}};OutlinedTextField(days,{days=it.filter(Char::isDigit)},label={Text("Expected interval in days (optional)")});OutlinedTextField(notes,{notes=it},label={Text("Notes (optional)")});TextButton({template=true}){Icon(Icons.Default.AutoAwesome,null);Text("  Use a template")}}}},confirmButton={if(!template)Button({if(name.isNotBlank()&&cat!=null){vm.add(name,cat!!,days.toIntOrNull(),notes=notes);dismiss()}},enabled=name.isNotBlank()){Text("Add Item")}},dismissButton={TextButton(if(template){{template=false}}else dismiss){Text(if(template)"Back" else "Cancel")}})}

@Composable private fun DoneDialog(item:ItemSummary,dismiss:()->Unit,save:(Long,String,Long?,String)->Unit){var note by remember{mutableStateOf("")};var cost by remember{mutableStateOf("")};var measure by remember{mutableStateOf("")};var daysAgo by remember{mutableStateOf("")};val days=daysAgo.toLongOrNull()?.coerceAtLeast(0)?:0;AlertDialog(onDismissRequest=dismiss,title={Text("Record completion")},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){Text(item.item.name,fontWeight=FontWeight.Bold);OutlinedTextField(daysAgo,{daysAgo=it.filter(Char::isDigit)},label={Text("Days ago (blank means now)")},supportingText={Text(if(days==0L)"Today" else "$days days ago")});OutlinedTextField(note,{note=it},label={Text("Optional note")});OutlinedTextField(cost,{cost=it.filter{c->c.isDigit()||c=='.'}},label={Text("Optional cost")});OutlinedTextField(measure,{measure=it},label={Text("Optional measurement")})}},confirmButton={Button({save(System.currentTimeMillis()-Duration.ofDays(days).toMillis(),note,(cost.toDoubleOrNull()?.times(100))?.toLong(),measure)}){Text("Record completion")}},dismissButton={TextButton(dismiss){Text("Cancel")}})}

@OptIn(ExperimentalMaterial3Api::class) @Composable private fun DetailScreen(id:Long,vm:LastDoneViewModel,back:()->Unit,done:(ItemSummary)->Unit){
 val summary by vm.item(id).collectAsState(initial=null);val history by vm.itemHistory(id).collectAsState(initial=emptyList());val s=summary?:return
 var editing by remember{mutableStateOf<CompletionRecord?>(null)};var deleting by remember{mutableStateOf<CompletionRecord?>(null)}
 val intervals=LastDoneCalculations.intervals(history.map{it.completedAt})
 Scaffold(topBar={TopAppBar(title={Text(s.item.name,maxLines=1)},navigationIcon={IconButton(back){Icon(Icons.Default.ArrowBack,"Back")}})},floatingActionButton={ExtendedFloatingActionButton(text={Text("Done Now")},icon={Icon(Icons.Default.Check,null)},onClick={done(s)})}){pad->
  LazyColumn(Modifier.padding(pad),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
   item{Text(LastDoneCalculations.elapsedLabel(s.lastDone),style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.Bold);Text(s.lastDone?.let{DateFormat.getDateTimeInstance().format(Date(it))}?:"No history recorded yet")}
   item{Card{Column(Modifier.padding(16.dp)){Text("Overview",fontWeight=FontWeight.Bold);Text("Expected interval: ${s.item.expectedDays?.let{"$it days"}?:"No schedule"}");Text("Average interval: ${intervals.takeIf{it.isNotEmpty()}?.average()?.toInt()?.let{"$it days"}?:"Not enough history"}");Text("Shortest: ${intervals.minOrNull()?.let{"$it days"}?:"—"}");Text("Longest: ${intervals.maxOrNull()?.let{"$it days"}?:"—"}");Text("Next suggested: ${LastDoneCalculations.nextSuggested(s.lastDone,s.item.expectedDays)?.let{DateFormat.getDateInstance().format(Date(it))}?:"—"}")}}}
   item{Text("Completion history",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)}
   if(history.isEmpty())item{EmptyCard("No history recorded yet","Tap Done Now when you complete this item.")}
   items(history,key={it.id}){r->Card{Column(Modifier.fillMaxWidth().padding(14.dp)){Text(DateFormat.getDateTimeInstance().format(Date(r.completedAt)),fontWeight=FontWeight.Bold);if(r.note.isNotBlank())Text(r.note);r.costCents?.let{Text("Cost: USD ${"%.2f".format(it/100.0)}")};if(r.measurement.isNotBlank())Text("Measurement: ${r.measurement}");Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.End){IconButton({editing=r}){Icon(Icons.Default.Edit,"Edit completion")};IconButton({vm.duplicateCompletion(r)}){Icon(Icons.Default.ContentCopy,"Duplicate completion")};IconButton({deleting=r}){Icon(Icons.Default.Delete,"Delete completion")}}}}}
   item{HorizontalDivider();TextButton({vm.archive(id);back()}){Text("Archive item")};Text("Items with history are archived instead of silently deleting their records.",style=MaterialTheme.typography.bodySmall)}
  }
 }
 editing?.let{record->EditCompletionDialog(record,{editing=null}){updated->vm.updateCompletion(updated);editing=null}}
 deleting?.let{record->AlertDialog(onDismissRequest={deleting=null},title={Text("Delete this completion?")},text={Text("Elapsed time, averages, costs, status, and the next suggested date will be recalculated.")},confirmButton={Button({vm.deleteCompletion(record);deleting=null}){Text("Delete")}},dismissButton={TextButton({deleting=null}){Text("Cancel")}})}
}

@Composable private fun EditCompletionDialog(record:CompletionRecord,dismiss:()->Unit,save:(CompletionRecord)->Unit){
 var daysAgo by remember{mutableStateOf(Duration.between(Instant.ofEpochMilli(record.completedAt),Instant.now()).toDays().coerceAtLeast(0).toString())};var note by remember{mutableStateOf(record.note)};var cost by remember{mutableStateOf(record.costCents?.let{"%.2f".format(Locale.US,it/100.0)}?:"")};var measurement by remember{mutableStateOf(record.measurement)}
 AlertDialog(onDismissRequest=dismiss,title={Text("Edit completion")},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(daysAgo,{daysAgo=it.filter(Char::isDigit)},label={Text("Days ago")});OutlinedTextField(note,{note=it},label={Text("Note")});OutlinedTextField(cost,{cost=it.filter{c->c.isDigit()||c=='.'}},label={Text("Cost")});OutlinedTextField(measurement,{measurement=it},label={Text("Measurement")})}},confirmButton={Button({val date=System.currentTimeMillis()-Duration.ofDays(daysAgo.toLongOrNull()?:0).toMillis();save(record.copy(completedAt=date,note=note,costCents=(cost.toDoubleOrNull()?.times(100))?.toLong(),measurement=measurement))}){Text("Save changes")}},dismissButton={TextButton(dismiss){Text("Cancel")}})
}

@Composable private fun HistoryScreen(vm:LastDoneViewModel){val records by vm.history.collectAsState();val items by vm.items.collectAsState();LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("History",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Most recently completed")};items(records){r->Card{Column(Modifier.padding(14.dp)){Text(items.firstOrNull{it.item.id==r.itemId}?.item?.name?:"Archived item",fontWeight=FontWeight.Bold);Text(DateFormat.getDateTimeInstance().format(Date(r.completedAt)));if(r.note.isNotBlank())Text(r.note)}}}}}
@Composable private fun SettingsScreen(vm:LastDoneViewModel){val s by vm.settings.collectAsState();val activity=LocalContext.current as MainActivity;LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Settings",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold)};item{Card{Column(Modifier.padding(16.dp)){Text("Appearance",fontWeight=FontWeight.Bold);Row(verticalAlignment=Alignment.CenterVertically){Text("Dark mode",Modifier.weight(1f));Switch(s.darkMode,{vm.dark(it)})}}}};item{Card{Column(Modifier.padding(16.dp)){Text("Default completion behavior",fontWeight=FontWeight.Bold);CompletionMode.entries.forEach{m->Row(Modifier.fillMaxWidth().clickable{vm.mode(m)}.padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically){RadioButton(s.completionMode==m,{vm.mode(m)});Text(m.name.lowercase().replace('_',' ').replaceFirstChar(Char::uppercase))}}}}};item{Card{Column(Modifier.padding(16.dp)){Text("Reminders",fontWeight=FontWeight.Bold);Text("LastDone uses reliable local WorkManager notifications.");Button({vm.testReminder()}){Text("Send test reminder")};Text("The test notification should appear in a few seconds.",style=MaterialTheme.typography.bodySmall)}}};item{Card{Column(Modifier.padding(16.dp)){Text("Data and privacy",fontWeight=FontWeight.Bold);Text("Your data stays on this device unless you explicitly export it.");Button({activity.exportBackup()}){Text("Create JSON backup")};TextButton({activity.exportCsv()}){Text("Export history CSV")};TextButton({activity.restoreBackup()}){Text("Restore validated backup")};TextButton({vm.demo()}){Text("Load demo data")};Text("Restore validates the file and asks before replacing current data. Photo-inclusive backup and merge restore remain planned refinements.",style=MaterialTheme.typography.bodySmall)}}};item{Text("LastDone v0.1.2\nSmithware Studios",style=MaterialTheme.typography.bodyMedium)}}}
@Composable private fun EmptyCard(title:String,body:String){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(20.dp)){Text(title,fontWeight=FontWeight.Bold);Text(body)}}}

private object Templates{val groups=linkedMapOf("HOME MAINTENANCE" to listOf("Change HVAC filter","Test smoke detectors","Replace smoke-detector batteries","Clean dryer vent","Clean refrigerator coils","Flush water heater","Clean gutters","Check fire extinguisher","Replace water filter","Inspect plumbing leaks"),"CLEANING" to listOf("Clean oven","Deep-clean refrigerator","Clean coffee maker","Wash pillows","Wash bedding","Clean washing machine","Clean dishwasher","Clean ceiling fans","Clean windows","Clean under furniture"),"VEHICLE" to listOf("Oil change","Tire rotation","Check tire pressure","Replace windshield wipers","Vehicle inspection","Replace cabin air filter","Replace engine air filter","Wash vehicle","Check fluid levels","Renew registration"),"HEALTH AND PERSONAL CARE" to listOf("Dental cleaning","Eye exam","Physical exam","Replace toothbrush","Haircut","Review prescriptions","Check first-aid supplies"),"PETS" to listOf("Flea treatment","Nail trim","Bath","Vet visit","Replace pet bedding","Clean aquarium","Grooming appointment","Order pet medication"),"TECHNOLOGY" to listOf("Back up computer","Back up phone","Change important password","Update emergency recovery codes","Clean keyboard","Clean computer fans","Review subscriptions","Review storage space","Test backup restoration","Replace batteries"),"RELATIONSHIPS AND PERSONAL MEMORY" to listOf("Called parent","Called grandparent","Contacted friend","Visited family member","Planned date night","Sent thank-you message","Checked in with someone","Visited favorite location","Took a personal day","Reviewed personal goals"))}
